<Project Sdk="Microsoft.NET.Sdk.Worker">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>dotnet-Payments.Worker-79650536-d020-45b0-90fe-037416761b53</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="9.0.19" />
    <PackageReference Include="Microsoft.Extensions.Http.Resilience" Version="9.10.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Payments.Core\Payments.Core.csproj" />
  </ItemGroup>
</Project>
