-- mini-psp initial schema
--
-- Conventions:
--   * Money is an integer count of minor units (cents, kopiyky) plus an ISO 4217
--     code. Never a floating point type. See docs/adr/0002-money-as-minor-units.md
--   * Status is text + CHECK rather than a PostgreSQL ENUM: adding a value to an
--     ENUM needs ALTER TYPE, which is awkward to roll out. Storage cost is
--     negligible at this size.
--   * Every table carries created_at; mutable rows also carry updated_at.

BEGIN;

CREATE TABLE payments (
    id                  uuid        PRIMARY KEY,
    merchant_id         uuid        NOT NULL,
    status              text        NOT NULL,
    amount_minor        bigint      NOT NULL,
    -- text, not char(3): char pads with spaces, so 'US' would be stored as
    -- 'US ' and pass any check that only compares case. The pattern constrains
    -- length, alphabet and case in one place.
    currency            text        NOT NULL,
    provider            text        NULL,
    provider_payment_id text        NULL,
    -- Optimistic concurrency. Written by the domain on every transition; no
    -- UPDATE path exists yet, so nothing asserts it in SQL so far.
    version             integer     NOT NULL DEFAULT 1,
    created_at          timestamptz NOT NULL DEFAULT now(),
    updated_at          timestamptz NOT NULL DEFAULT now(),

    CONSTRAINT payments_status_allowed CHECK (status IN (
        'created', 'pending', 'authorized', 'captured',
        'failed', 'expired', 'unknown', 'refunded'
    )),
    CONSTRAINT payments_amount_positive CHECK (amount_minor > 0),
    CONSTRAINT payments_currency_iso    CHECK (currency ~ '^[A-Z]{3}$')
);

-- Partial index for background work: the states a sweeper or a reconciliation
-- job may still need to act on. Terminal rows accumulate forever and would
-- otherwise dominate an index that never returns them.
-- The predicate encodes a business fact, so widening it needs a migration.
CREATE INDEX payments_actionable_idx
    ON payments (status, created_at)
    WHERE status IN ('created', 'pending', 'authorized', 'unknown');

-- "This merchant's payments, newest first" is the most common read in a PSP.
CREATE INDEX payments_merchant_recent_idx
    ON payments (merchant_id, created_at DESC);

-- Idempotency lives in PostgreSQL, not Redis, because the key must be claimed
-- in the same transaction that inserts the payment: one commit either produces
-- both rows or neither. See docs/adr/0003-idempotency-in-postgres.md
CREATE TABLE idempotency_keys (
    merchant_id     uuid        NOT NULL,
    idempotency_key text        NOT NULL,
    -- Hash of the canonical request body. Same key with a different body is a
    -- client bug, not a retry, and must be rejected rather than served the old
    -- response.
    request_hash    text        NOT NULL,
    payment_id      uuid        NOT NULL REFERENCES payments (id),
    response_status integer     NOT NULL,
    -- text, not jsonb: jsonb reparses and reorders keys, so a replayed body
    -- would not be the bytes the first request returned. The body is opaque
    -- here and is never queried by content, only handed back verbatim.
    response_body   text        NOT NULL,
    created_at      timestamptz NOT NULL DEFAULT now(),

    PRIMARY KEY (merchant_id, idempotency_key)
);

-- PostgreSQL does not index a foreign key column automatically, and without
-- this every delete from payments scans this table.
CREATE INDEX idempotency_keys_payment_idx ON idempotency_keys (payment_id);

-- Transactional outbox. The state change and the event it produces are written
-- in ONE transaction; a dispatcher publishes to Kafka afterwards.
-- See docs/adr/0001-transactional-outbox.md
CREATE TABLE outbox (
    id           bigint      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    aggregate_id uuid        NOT NULL,
    event_type   text        NOT NULL,
    payload      jsonb       NOT NULL,
    created_at   timestamptz NOT NULL DEFAULT now(),
    published_at timestamptz NULL
);

-- Partial index: the dispatcher only ever reads unpublished rows, so published
-- ones must not bloat the index it scans.
CREATE INDEX outbox_unpublished_idx
    ON outbox (created_at)
    WHERE published_at IS NULL;

COMMIT;
