-- Double entry ledger.
--
-- Balances are not stored. They are derived by summing entries, because a stored
-- balance is a second version of the truth that can disagree with the entries
-- that produced it, and reconciling those two is a job nobody wants.
--
-- Amounts are signed. A transaction is a set of entries that sum to zero, which
-- is what "money is moved, never created" means when written as an invariant.

CREATE TABLE ledger_accounts (
    -- Readable and derivable: 'merchant:<uuid>', 'provider:<name>', 'fees'.
    -- A natural key means posting an entry never needs a lookup first.
    id         text        PRIMARY KEY,
    kind       text        NOT NULL,
    currency   text        NOT NULL,
    created_at timestamptz NOT NULL DEFAULT now(),

    CONSTRAINT ledger_accounts_kind_allowed CHECK (kind IN ('merchant', 'provider', 'fees')),
    CONSTRAINT ledger_accounts_currency_iso CHECK (currency ~ '^[A-Z]{3}$')
);

-- One movement of money, made of the entries that describe it.
CREATE TABLE ledger_transactions (
    id         uuid        PRIMARY KEY,
    payment_id uuid        NOT NULL REFERENCES payments (id),
    kind       text        NOT NULL,
    created_at timestamptz NOT NULL DEFAULT now(),

    CONSTRAINT ledger_transactions_kind_allowed CHECK (kind IN ('capture', 'refund')),

    -- The idempotency guard, and the reason posting twice is safe: a payment can
    -- be captured once. A redelivered event meets this index rather than
    -- doubling the merchant's balance.
    CONSTRAINT ledger_transactions_once UNIQUE (payment_id, kind)
);

CREATE TABLE ledger_entries (
    id             bigint      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    transaction_id uuid        NOT NULL REFERENCES ledger_transactions (id),
    account_id     text        NOT NULL REFERENCES ledger_accounts (id),
    -- Signed: negative takes from the account, positive gives to it. Zero says
    -- nothing and is refused, because an entry that moves nothing is a mistake
    -- somewhere upstream.
    amount_minor   bigint      NOT NULL,
    currency       text        NOT NULL,
    created_at     timestamptz NOT NULL DEFAULT now(),

    CONSTRAINT ledger_entries_nonzero CHECK (amount_minor <> 0),
    CONSTRAINT ledger_entries_currency_iso CHECK (currency ~ '^[A-Z]{3}$')
);

-- Deriving a balance means summing an account's entries, so that is the access
-- pattern worth indexing.
CREATE INDEX ledger_entries_account_idx ON ledger_entries (account_id, id);
CREATE INDEX ledger_entries_transaction_idx ON ledger_entries (transaction_id);

-- The invariant, enforced by the database rather than trusted to the code.
--
-- A CHECK cannot express it: it is a property of a set of rows, not of one. A
-- constraint trigger can, and DEFERRABLE INITIALLY DEFERRED makes it run at
-- COMMIT, so entries are inserted one at a time and the balance is judged once
-- they are all there.
--
-- This is what stops a bug from creating money. Application code can be wrong;
-- an unbalanced transaction still will not commit.
CREATE FUNCTION ledger_transaction_balances() RETURNS trigger AS $$
DECLARE
    -- Not named transaction_id: a plpgsql variable sharing a column's name makes
    -- every reference to it ambiguous inside the query below.
    txn_id uuid := COALESCE(NEW.transaction_id, OLD.transaction_id);
    total bigint;
    currencies int;
BEGIN
    SELECT sum(amount_minor), count(DISTINCT currency)
    INTO total, currencies
    FROM ledger_entries e
    WHERE e.transaction_id = txn_id;

    IF currencies > 1 THEN
        RAISE EXCEPTION 'ledger transaction % mixes % currencies', txn_id, currencies
            USING ERRCODE = 'check_violation';
    END IF;

    IF total <> 0 THEN
        RAISE EXCEPTION 'ledger transaction % does not balance, off by %', txn_id, total
            USING ERRCODE = 'check_violation';
    END IF;

    RETURN NULL;
END;
$$ LANGUAGE plpgsql;

CREATE CONSTRAINT TRIGGER ledger_entries_balance
    AFTER INSERT OR UPDATE OR DELETE ON ledger_entries
    DEFERRABLE INITIALLY DEFERRED
    FOR EACH ROW EXECUTE FUNCTION ledger_transaction_balances();
